#!/usr/bin/env python3
"""Generate the reviewable 19-node FlowMesh definition from a frozen bundle."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
import yaml
from platform_integration.research_audit import DEPENDENCIES, load_manifest

IMAGE = "harbor.lum.id/cyx-fyp/representation-learning-framework:research-audit-v0.3.0"


class Dumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


def represent_string(dumper, value):
    return dumper.represent_scalar("tag:yaml.org,2002:str", value,
                                   style="|" if "\n" in value else None)


Dumper.add_representer(str, represent_string)


def workflow_text(bundle: Path, image: str = IMAGE) -> str:
    manifest, bundle_id = load_manifest(bundle)
    nodes = []
    for name, deps in DEPENDENCIES.items():
        code = ("def main(**kwargs):\n"
                "    from platform_integration.research_audit import run_node\n"
                f"    return run_node({name!r}, inputs=kwargs,\n"
                f"                    expected_bundle_id={bundle_id!r})\n")
        nodes.append({"name": name, "dependsOn": list(deps), "spec": {
            "taskType": "python", "image": image, "entrypoint": "main",
            "emits": manifest["nodes"][name]["emits"], "timeoutSeconds": 300,
            "network": "none", "resources": {"hardware": {
                "cpu": 1, "memory": "2Gi", "gpu": {"type": "any", "count": 1}}},
            "pythonOutput": {"maxBytes": 4194304}, "code": code,
        }})
    document = {"apiVersion": "flowmesh/v1", "kind": "Task", "metadata": {
        "name": "fyp-research-evidence-audit", "annotations": {
            "description": "Six-stage research evidence demonstration: canonical framework, encoder variants, frozen representations, task benchmarks, and synthesis; no training.",
        }}, "spec": {"graph": {"nodes": nodes}}}
    return ("# Generated by scripts/generate_research_audit_workflow.py.\n"
            "# Frozen report/manifest inspection; no training or checkpoint inference.\n"
            "# spec.graph node name/spec/dependsOn matches the Studio editor serializer.\n"
            f"# Evidence bundle: {bundle_id}\n"
            f"# Source revision: {manifest['source_revision']}\n"
            + yaml.dump(document, Dumper=Dumper, sort_keys=False, width=120))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle-dir", type=Path, default=ROOT / "build/flowmesh-research-evidence")
    parser.add_argument("--output", type=Path, default=ROOT / "workflows/flowmesh_research_audit.yaml")
    parser.add_argument("--image", default=IMAGE)
    parser.add_argument("--check", action="store_true", help="Check deterministic generation without writing")
    args = parser.parse_args()
    content = workflow_text(args.bundle_dir, args.image)
    if args.check:
        if args.output.read_text() != content:
            raise SystemExit("Workflow differs from its frozen bundle or generator")
        print("Workflow generation matches")
    else:
        args.output.write_text(content)
        print(args.output)


if __name__ == "__main__":
    main()
